# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 
  khlas_secret_test: 
  khlas_publishable_test: 
  bareed_key: 

test:
  secret_key_base: 
  khlas_secret_test: 
  khlas_publishable_test: 
  bareed_key:

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  khlas_secret_live: <%= ENV['KHLAS_SECRET_LIVE'] %>
  khlas_publishable_live: <%= ENV['KHLAS_PUBLISHABLE_LIVE'] %>
  bareed_key: <%= ENV['BAREED_KEY'] %>